version: '3'
services:
  mosquitto:
    build:
      context: ./mosquitto
    ports:
    - "1883:1883"

  mysql:
    build:
      context: ./mysql
    ports:
    - "3306:3306"
    
  iotclient:
    build:
      context: ./IOTclient

  iotserver:
    build:
      context: ./IOTserver

  backend:
    build:
      context: ./backend
    ports:
    - "5000:5000"

  front:
    build:
      context: ./frontend
    ports:
    - "8080:80"
